const moduloA = require('./moduloA')
const moduloB = require('./moduloB')
const s = require('saudacao')

console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log(moduloA)
console.log(moduloB.bomDia)
console.log(moduloB.boaNoite())
console.log(moduloB)
console.log(s.ola)
